title: L3C Wiki
description: Uma wiki para os projetos do Laboratório de Conexionismo e Ciências Cognitivas da UFSC
permalink: none
show_comments: false
git_branch: gh-pages
logo_url: assets/images/l3cicon.png
google_analytics:
theme:
markdown: kramdown
custom_head: false
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
